import { memo } from 'react'
import { CarFront, CalendarRange, ChevronLeft, ChevronRight } from 'lucide-react'
import { reimbursementStatusLabel } from '../records'
import type { OvertimeRecord } from '../types'

type MonthOverviewProps = { records: OvertimeRecord[]; selectedMonth: string; mode: 'month' | 'year'; onMonthChange: (month: string) => void; onModeChange: (mode: 'month' | 'year') => void }
const weekdays = ['一', '二', '三', '四', '五', '六', '日']
const pad = (value: number) => String(value).padStart(2, '0')

export const MonthOverview = memo(function MonthOverview({ records, selectedMonth, mode, onMonthChange, onModeChange }: MonthOverviewProps) {
  const now = selectedMonth ? new Date(`${selectedMonth}-01T12:00:00`) : new Date()
  const year = now.getFullYear()
  const month = now.getMonth()
  const monthKey = `${year}-${pad(month + 1)}`
  const yearKey = String(year)
  const firstOffset = (new Date(year, month, 1).getDay() + 6) % 7
  const days = new Date(year, month + 1, 0).getDate()
  const recordMap = new Map(records.filter((record) => record.date.startsWith(mode === 'year' ? yearKey : monthKey)).map((record) => [record.date, record]))
  const cells = Array.from({ length: Math.ceil((firstOffset + days) / 7) * 7 }, (_, index) => index - firstOffset + 1)
  const shiftPeriod = (offset: number) => { const next = new Date(year + (mode === 'year' ? offset : 0), month + (mode === 'year' ? 0 : offset), 1); onMonthChange(`${next.getFullYear()}-${pad(next.getMonth() + 1)}`) }
  const periodRecords = records.filter((record) => record.date.startsWith(mode === 'year' ? yearKey : monthKey))
  const taxiTotal = periodRecords.filter((record) => record.tookTaxi).reduce((sum, record) => sum + record.taxiCost, 0)
  if (mode === 'year') return <section className="month-overview"><div className="overview-heading"><div><span className="section-kicker">日历总览</span><h2>{year}年，哪几天加了班</h2></div><div className="month-navigator"><button type="button" onClick={() => shiftPeriod(-1)} aria-label="上一年"><ChevronLeft size={18} /></button><label><CalendarRange size={15} /><span>{year}年</span><input type="number" min="2000" max="2100" value={year} onChange={(event) => onMonthChange(`${event.target.value}-${pad(month + 1)}`)} aria-label="选择统计年份" /></label><button type="button" onClick={() => shiftPeriod(1)} aria-label="下一年"><ChevronRight size={18} /></button><button type="button" className="overview-mode-toggle" onClick={() => onModeChange('month')}>按月</button></div></div><div className="year-overview-grid">{Array.from({ length: 12 }, (_, index) => { const itemMonth = index + 1; const monthly = records.filter((record) => record.date.startsWith(`${yearKey}-${pad(itemMonth)}`)); const taxis = monthly.filter((record) => record.tookTaxi).reduce((sum, record) => sum + record.taxiCost, 0); return <button type="button" className={`year-overview-month ${monthly.length ? 'has-record' : ''}`} key={itemMonth} onClick={() => { onModeChange('month'); onMonthChange(`${yearKey}-${pad(itemMonth)}`) }}><strong>{itemMonth}月</strong><span>{monthly.length} 天加班</span><small>{taxis ? `打车 ¥${taxis.toFixed(0)}` : '无打车'}</small></button> })}</div><div className="overview-legend"><span><i className="legend-dot legend-dot--overtime" />加班日</span><span className="overview-total">全年打车费用 ¥{taxiTotal.toFixed(0)}</span></div></section>
  return <section className="month-overview"><div className="overview-heading"><div><span className="section-kicker">日历总览</span><h2>这个月，哪几天加了班</h2></div><div className="month-navigator"><button type="button" onClick={() => shiftPeriod(-1)} aria-label="上个月"><ChevronLeft size={18} /></button><label><CalendarRange size={15} /><span>{year}年{month + 1}月</span><input type="month" value={selectedMonth} onChange={(event) => onMonthChange(event.target.value)} aria-label="选择统计月份" /></label><button type="button" onClick={() => shiftPeriod(1)} aria-label="下个月"><ChevronRight size={18} /></button><button type="button" className="overview-mode-toggle" onClick={() => onModeChange('year')}>按年</button></div></div><div className="calendar-grid calendar-grid--overview calendar-grid--head">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid calendar-grid--overview">{cells.map((day, index) => { if (day < 1 || day > days) return <span className="overview-empty" key={`empty-${index}`} />; const date = `${year}-${pad(month + 1)}-${pad(day)}`; const record = recordMap.get(date); return <div className={`overview-day ${record ? 'has-record' : ''}`} key={date}><strong>{day}</strong>{record && <div className="overview-day__meta"><span>加班</span>{record.tookTaxi && <><span className={`overview-day__status overview-day__status--${record.reimbursementStatus || 'unsubmitted'}`}>{reimbursementStatusLabel(record.reimbursementStatus)}</span><span className="overview-day__taxi"><CarFront size={11} />¥{record.taxiCost.toFixed(0)}</span></>}</div>}</div> })}</div><div className="overview-legend"><span><i className="legend-dot legend-dot--overtime" />加班日</span><span><i className="legend-dot legend-dot--taxi" />含打车费用</span><span className="overview-total">本月打车费用 ¥{taxiTotal.toFixed(0)}</span></div></section>
})
